#!/usr/bin/env python3
"""
Generate src/voltra/sweep_params.cpp for the diagnostic build (env:remote_diag), which
reads the listed registers periodically so changes can be found by diffing snapshots
taken in different device states.

Two modes:
  documented    every BP and MC id in the vendor dictionary
  undocumented  ids in 0x5300-0x57FF that the dictionary does NOT list; newer firmware
                features appear here because the dictionary predates them
  settings      the documented BP ids followed by the undocumented range, for hunting a
                device setting that could live in either

Usage: python tools/gen_sweep_params.py path/to/paramInfo.csv [documented|undocumented]
"""
import csv
import sys

CATEGORIES = {"BP", "MC"}

MODE = sys.argv[2] if len(sys.argv) > 2 else "documented"
all_rows = list(csv.DictReader(open(sys.argv[1], encoding="utf-8")))
known = {int(r["id"]) for r in all_rows}
undocumented = [i for i in range(0x5300, 0x5800) if i not in known]
if MODE == "undocumented":
    ids = undocumented
    describe = f"{len(ids)} undocumented ids in 0x5300-0x57FF"
elif MODE == "settings":
    bp = sorted({int(r["id"]) for r in all_rows if r["category"] == "BP"})
    ids = bp + undocumented
    describe = f"{len(bp)} BP ids then {len(undocumented)} undocumented ids in 0x5300-0x57FF"
else:
    ids = sorted({int(r["id"]) for r in all_rows if r["category"] in CATEGORIES})
    describe = f"{len(ids)} BP and MC parameter ids"

lines = []
for i in range(0, len(ids), 12):
    lines.append("    " + ", ".join(f"0x{x:04X}" for x in ids[i:i + 12]) + ",")

out = f"""// Generated by tools/gen_sweep_params.py - do not edit.
// {describe}, read by the diagnostic build only.
#include "sweep_params.h"

#if VOLTRA_DIAG
namespace voltra {{

const uint16_t SWEEP_PARAMS[] = {{
{chr(10).join(lines)}
}};
const size_t SWEEP_PARAM_COUNT = sizeof(SWEEP_PARAMS) / sizeof(SWEEP_PARAMS[0]);

}}  // namespace voltra
#endif
"""
open("src/voltra/sweep_params.cpp", "w", newline="\n").write(out)
print(f"wrote src/voltra/sweep_params.cpp with {len(ids)} ids")
