#!/usr/bin/env python3
"""
Minimal LVGL v8 bitmap-font generator (4 bpp, no kerning) using Pillow.

Produces the same lv_font_fmt_txt structures as lv_font_conv so that the
firmware can use a big digit font without needing Node.js.

Usage:
  python gen_font.py --ttf Montserrat-Medium.ttf --size 96 \
      --chars "0123456789-+" --name font_weight_96 --out ../src/ui/fonts/font_weight_96.c

--ascii adds the printable ASCII range; --fallback names a font LVGL falls back to for
glyphs this one lacks (e.g. lv_font_montserrat_16 for the LV_SYMBOL_* icons).
"""
import argparse
import os
import sys

from PIL import Image, ImageDraw, ImageFont

BPP = 4


def render_glyph(font, ch):
    # bbox relative to the (left, baseline) anchor; y grows downward in image space
    x0, y0, x1, y1 = font.getbbox(ch, anchor="ls")
    box_w, box_h = x1 - x0, y1 - y0
    adv = font.getlength(ch)
    if box_w <= 0 or box_h <= 0:
        return b"", 0, 0, 0, 0, adv
    img = Image.new("L", (box_w, box_h), 0)
    ImageDraw.Draw(img).text((-x0, -y0), ch, font=font, fill=255, anchor="ls")
    ofs_x = x0
    ofs_y = -y1  # distance from baseline up to bottom of the box (0 for digits)
    return pack_4bpp(img), box_w, box_h, ofs_x, ofs_y, adv


def pack_4bpp(img):
    """Pack an "L" image as LVGL 4 bpp glyph data: MSB first, rows continuous, byte padded."""
    px = img.load()
    w, h = img.size
    bits = [round(px[x, y] * 15 / 255) for y in range(h) for x in range(w)]
    out = bytearray()
    for i in range(0, len(bits), 2):
        hi = bits[i]
        lo = bits[i + 1] if i + 1 < len(bits) else 0
        out.append((hi << 4) | lo)
    return bytes(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--ttf", required=True)
    ap.add_argument("--size", type=int, required=True)
    ap.add_argument("--chars", default="")
    ap.add_argument("--ascii", action="store_true", help="include printable ASCII (0x20-0x7E)")
    ap.add_argument("--fallback", help="LVGL font to fall back to for missing glyphs")
    ap.add_argument("--name", required=True)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    font = ImageFont.truetype(a.ttf, a.size)
    ascent, descent = font.getmetrics()
    chars = set(a.chars)
    if a.ascii:
        chars |= {chr(c) for c in range(0x20, 0x7F)}
    chars = sorted(chars, key=ord)

    glyphs = [(ord(ch), ch) + render_glyph(font, ch) for ch in chars]
    shown = "printable ASCII" + (" + " + a.chars if a.chars else "") if a.ascii else "".join(chars)
    source = f"{a.ttf.split('/')[-1]} (chars: \"{shown}\")"
    write_font(a.out, a.name, a.size, source, glyphs, ascent + descent, descent, a.fallback)


def comment_label(label):
    """Glyph name for a C comment; characters that could end or disturb it are omitted."""
    return "" if any(c in label for c in "*/\\") else "'" + label + "'"


def write_font(out_path, name, size, source, glyphs, line_height, base_line, fallback=None):
    """
    Emit an lv_font_fmt_txt font (one sparse cmap, no kerning).

    glyphs: (codepoint, label, bitmap, box_w, box_h, ofs_x, ofs_y, adv_px), sorted by codepoint.
    """
    tool = os.path.basename(sys.argv[0])
    bitmap = bytearray()
    dscs = ["    {.bitmap_index = 0, .adv_w = 0, .box_w = 0, .box_h = 0, .ofs_x = 0, .ofs_y = 0} /* id = 0 reserved */"]
    for cp, label, data, bw, bh, ox, oy, adv in glyphs:
        dscs.append(
            f"    {{.bitmap_index = {len(bitmap)}, .adv_w = {round(adv * 16)}, .box_w = {bw}, .box_h = {bh}, "
            f".ofs_x = {ox}, .ofs_y = {oy}}} /* U+{cp:04X} {comment_label(label)} */"
        )
        bitmap += data

    range_start = glyphs[0][0]
    range_len = glyphs[-1][0] - range_start + 1
    unicode_list = ", ".join(str(g[0] - range_start) for g in glyphs)

    hexdump = []
    for i in range(0, len(bitmap), 16):
        hexdump.append("    " + ", ".join(f"0x{b:02x}" for b in bitmap[i:i + 16]) + ",")

    c = f"""/*******************************************************************************
 * Size: {size} px
 * Bpp: {BPP}
 * Opts: generated by tools/{tool} from {source}
 ******************************************************************************/

#ifdef LV_LVGL_H_INCLUDE_SIMPLE
#include "lvgl.h"
#else
#include "lvgl/lvgl.h"
#endif

#ifndef {name.upper()}
#define {name.upper()} 1
#endif

#if {name.upper()}

/*-----------------
 *    BITMAPS
 *----------------*/

/*Store the image of the glyphs*/
static LV_ATTRIBUTE_LARGE_CONST const uint8_t glyph_bitmap[] = {{
{chr(10).join(hexdump)}
}};

/*---------------------
 *  GLYPH DESCRIPTION
 *--------------------*/

static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {{
{(','+chr(10)).join(dscs)}
}};

/*---------------------
 *  CHARACTER MAPPING
 *--------------------*/

static const uint16_t unicode_list_0[] = {{
    {unicode_list}
}};

/*Collect the unicode lists and glyph_id offsets*/
static const lv_font_fmt_txt_cmap_t cmaps[] = {{
    {{
        .range_start = {range_start}, .range_length = {range_len}, .glyph_id_start = 1,
        .unicode_list = unicode_list_0, .glyph_id_ofs_list = NULL, .list_length = {len(glyphs)}, .type = LV_FONT_FMT_TXT_CMAP_SPARSE_TINY
    }}
}};

/*--------------------
 *  ALL CUSTOM DATA
 *--------------------*/

#if LVGL_VERSION_MAJOR == 8
/*Store all the custom data of the font*/
static  lv_font_fmt_txt_glyph_cache_t cache;
#endif

#if LVGL_VERSION_MAJOR >= 8
static const lv_font_fmt_txt_dsc_t font_dsc = {{
#else
static lv_font_fmt_txt_dsc_t font_dsc = {{
#endif
    .glyph_bitmap = glyph_bitmap,
    .glyph_dsc = glyph_dsc,
    .cmaps = cmaps,
    .kern_dsc = NULL,
    .kern_scale = 0,
    .cmap_num = 1,
    .bpp = {BPP},
    .kern_classes = 0,
    .bitmap_format = 0,
#if LVGL_VERSION_MAJOR == 8
    .cache = &cache
#endif
}};

/*-----------------
 *  PUBLIC FONT
 *----------------*/

/*Initialize a public general font descriptor*/
#if LVGL_VERSION_MAJOR >= 8
const lv_font_t {name} = {{
#else
lv_font_t {name} = {{
#endif
    .get_glyph_dsc = lv_font_get_glyph_dsc_fmt_txt,    /*Function pointer to get glyph's data*/
    .get_glyph_bitmap = lv_font_get_bitmap_fmt_txt,    /*Function pointer to get glyph's bitmap*/
    .line_height = {line_height},          /*The maximum line height required by the font*/
    .base_line = {base_line},             /*Baseline measured from the bottom of the line*/
#if !(LVGL_VERSION_MAJOR == 6 && LVGL_VERSION_MINOR == 0)
    .subpx = LV_FONT_SUBPX_NONE,
#endif
#if LV_VERSION_CHECK(7, 4, 0) || LVGL_VERSION_MAJOR >= 8
    .underline_position = -{max(1, size // 12)},
    .underline_thickness = {max(1, size // 20)},
#endif
    .dsc = &font_dsc,          /*The custom font data. Will be accessed by `get_glyph_bitmap/dsc`*/
    .fallback = {"&" + fallback if fallback else "NULL"},
    .user_data = NULL
}};

#endif /*#if {name.upper()}*/
"""
    with open(out_path, "w", newline="\n") as f:
        f.write(c)
    print(f"wrote {out_path}: {len(glyphs)} glyphs, {len(bitmap)} bitmap bytes, "
          f"line_height={line_height}, base_line={base_line}")


if __name__ == "__main__":
    main()
